export const DEFAULT_EVENT_TYPES = [
  "Kids Birthdays",
  "Adult Birthdays",
  "Weddings",
  "Baby Showers",
  "Bridal Showers",
  "Graduations",
  "School Events",
  "Church Events",
  "Corporate Events",
  "Community Events",
  "Backyard Parties",
  "Holiday Parties",
  "Fundraisers",
  "Festivals",
  "Quinceaneras",
] as const;

export const DEFAULT_SERVICE_CATEGORIES = [
  "Bounce Houses",
  "Combo Bounce Houses",
  "Water Slides",
  "Obstacle Courses",
  "Toddler Units",
  "Interactive Games",
  "Carnival Games",
  "Concessions",
  "Tables and Chairs",
  "Tents",
  "Yard Games",
  "Foam Parties",
  "Photo Booths",
  "Generators",
  "Dunk Tanks",
] as const;
